### ISSUE TITLE
Issues 19 Oct

### ISSUE THREAD

**Issue by Afan417** [Fetii1/shfkforina2023#25]
- [x] About Section in mobile overflow (kto background vijat bojn overflow right-side, mund me ``overflow-hidden`` tprovojsh)

![Screenshot 2023-10-19 at 16 43 53](https://github.com/Fetii1/shfkforina2023/assets/45122414/7cfddff2-3cae-46fb-95e7-843d50a7f98c)

- [x] Active states missing in navigation (mobile and desktop)

When you are on "Galeria" text should be like in hover, blue something

- [x] Shembull dekush ka 4K monitor, aj da shofe ket foton kshtu: (easy fix oshte ta vendoj ncenter me ``mx-auto`` ose f``lex items-center justify-center``)

![Screenshot 2023-10-19 at 16 55 47](https://github.com/Fetii1/shfkforina2023/assets/45122414/ba3732ca-98dc-4b42-b9e4-1213329a48ab)

**Comment by Fetii1** [comment]
done
